### ISSUE TITLE
Will not compile with original board.

### ISSUE THREAD

**Issue by bsjoelund** [zombu2/Marlin-2.0-Anycubic-Chiron#1]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by zombu2** [comment]
Since this repo is for the SKR PRO and you clearly can not read or follow simple instructions i'm gonna close this
